modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-thevoiddimension/issues"
license = "ARR"

[[mods]]
modId = "thevoiddimension"
version = "${version}"
displayName = "The Void Dimension"
authors = "mahmudindev"
description = '''
Add the void superflat world type preset as separate dimension.
'''
logoFile = "assets/thevoiddimension/icon.png"

[[dependencies.thevoiddimension]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thevoiddimension]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thevoiddimension]]
modId = "dimensionfixer"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.thevoiddimension]]
modId = "worldportal"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"
