modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-thevoiddimension/issues"
license = "ARR"

[[mods]]
modId = "thevoiddimension"
version = "${version}"
displayName = "The Void Dimension"
authors = "mahmudindev"
description = '''
Add the void superflat world type preset as separate dimension.
'''
logoFile = "assets/thevoiddimension/icon.png"

[[dependencies.thevoiddimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thevoiddimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thevoiddimension]]
modId = "dimensionfixer"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.thevoiddimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "thevoiddimension.mixins.json"
